# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import api_pb2 as api__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class PodResourcesListerStub(object):
    """PodResourcesLister is a service provided by the kubelet that provides information about the
    node resources consumed by pods and containers on the node
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/v1.PodResourcesLister/List',
                request_serializer=api__pb2.ListPodResourcesRequest.SerializeToString,
                response_deserializer=api__pb2.ListPodResourcesResponse.FromString,
                _registered_method=True)
        self.GetAllocatableResources = channel.unary_unary(
                '/v1.PodResourcesLister/GetAllocatableResources',
                request_serializer=api__pb2.AllocatableResourcesRequest.SerializeToString,
                response_deserializer=api__pb2.AllocatableResourcesResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/v1.PodResourcesLister/Get',
                request_serializer=api__pb2.GetPodResourcesRequest.SerializeToString,
                response_deserializer=api__pb2.GetPodResourcesResponse.FromString,
                _registered_method=True)


class PodResourcesListerServicer(object):
    """PodResourcesLister is a service provided by the kubelet that provides information about the
    node resources consumed by pods and containers on the node
    """

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllocatableResources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PodResourcesListerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=api__pb2.ListPodResourcesRequest.FromString,
                    response_serializer=api__pb2.ListPodResourcesResponse.SerializeToString,
            ),
            'GetAllocatableResources': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllocatableResources,
                    request_deserializer=api__pb2.AllocatableResourcesRequest.FromString,
                    response_serializer=api__pb2.AllocatableResourcesResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=api__pb2.GetPodResourcesRequest.FromString,
                    response_serializer=api__pb2.GetPodResourcesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.PodResourcesLister', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.PodResourcesLister', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PodResourcesLister(object):
    """PodResourcesLister is a service provided by the kubelet that provides information about the
    node resources consumed by pods and containers on the node
    """

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.PodResourcesLister/List',
            api__pb2.ListPodResourcesRequest.SerializeToString,
            api__pb2.ListPodResourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllocatableResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.PodResourcesLister/GetAllocatableResources',
            api__pb2.AllocatableResourcesRequest.SerializeToString,
            api__pb2.AllocatableResourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.PodResourcesLister/Get',
            api__pb2.GetPodResourcesRequest.SerializeToString,
            api__pb2.GetPodResourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
