apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: billing-cronjob
spec:
  schedule: "0 0 * * *"  # Runs daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: billing-service
            image: your-billing-service-image
            env:
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: api-key
          restartPolicy: OnFailure

